"""initial_schema

Revision ID: 15013af93565
Revises: 
Create Date: 2026-06-27 22:55:46.075843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15013af93565'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('restaurants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('toast_location_guid', sa.String(length=100), nullable=True),
    sa.Column('square_location_id', sa.String(length=100), nullable=True),
    sa.Column('invoice_email_id', sa.String(length=50), nullable=True),
    sa.Column('food_cost_target_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('labor_cost_target_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('menu_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('menu_price', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('pos_name', sa.String(length=200), nullable=True),
    sa.Column('pos_item_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('business_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('daypart', sa.String(length=30), nullable=True),
    sa.Column('gross_revenue', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('net_revenue', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('covers', sa.Integer(), nullable=True),
    sa.Column('transactions', sa.Integer(), nullable=True),
    sa.Column('comps_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('voids_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('labor_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id', 'business_date')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vendors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('delivery_days', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('current_cost_per_unit', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('par_level', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('reorder_qty', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('current_stock', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pos_item_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('pos_system', sa.String(length=30), nullable=True),
    sa.Column('pos_item_name', sa.String(length=300), nullable=False),
    sa.Column('menu_item_id', sa.UUID(), nullable=True),
    sa.Column('is_ignored', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_by_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('menu_item_id', sa.UUID(), nullable=True),
    sa.Column('business_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quantity_sold', sa.Integer(), nullable=True),
    sa.Column('gross_revenue', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('food_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('raw_pos_name', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id', 'business_date')
    )
    op.create_table('vendor_invoices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_counts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('counted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('counted_by_user', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['counted_by_user'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_line_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('invoice_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('quantity_received', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('extended_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['vendor_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('menu_item_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('waste_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=True),
    sa.Column('cost_at_time', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("""
        SELECT create_hypertable('sales_summaries', 'business_date',
            chunk_time_interval => INTERVAL '1 month', if_not_exists => TRUE);
    """)
    op.execute("""
        SELECT create_hypertable('sales_by_item', 'business_date',
            chunk_time_interval => INTERVAL '1 month', if_not_exists => TRUE);
    """)
    op.create_index('ix_sales_summaries_rid_date', 'sales_summaries',
                    ['restaurant_id', 'business_date'])
    op.create_index('ix_sales_by_item_rid_date', 'sales_by_item',
                    ['restaurant_id', 'business_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('waste_logs')
    op.drop_table('recipe_lines')
    op.drop_table('invoice_line_items')
    op.drop_table('inventory_counts')
    op.drop_table('vendor_invoices')
    op.drop_table('sales_by_item')
    op.drop_table('pos_item_mappings')
    op.drop_table('ingredients')
    op.drop_table('vendors')
    op.drop_table('users')
    op.drop_table('sales_summaries')
    op.drop_table('menu_items')
    op.drop_table('restaurants')
    # ### end Alembic commands ###
